# Generated by Django 2.2.7 on 2020-01-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200111_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='mail',
            new_name='email',
        ),
    ]
